window.SEARCH_INDEX = [
  { title: "Gros œuvre", url: "gros-oeuvre.html", category: "Page", keywords: "gros oeuvre maçonnerie maconnerie beton béton ciment briques blocs planchers sable citerne" },
  { title: "Toitures", url: "toiture.html", category: "Page", keywords: "toiture toitures couverture velux epdm tôles toles zinc gouttiere gouttières étanchéité etancheite" },
  { title: "Aménagements", url: "amenagement-exterieur.html", category: "Page", keywords: "amenagement aménagement exterieur extérieur jardin terrasse pavés paves bordures seuils graviers chalet" },
  { title: "Sols", url: "sols.html", category: "Page", keywords: "sol sols carrelage carrelages parquet parquets vinyle stratifié stratifie" },
  { title: "Murs", url: "murs-interieurs.html", category: "Page", keywords: "murs mur intérieur interieur intérieurs interieurs plâtres platres tapisseries rocko" },
  { title: "Portes", url: "portes.html", category: "Page", keywords: "porte portes thys solid dors dor's" },
  { title: "Électricité", url: "electricite.html", category: "Page", keywords: "électricité electricite niko schneider legrand abb marlanvil teco" },
  { title: "Sanitaire", url: "sanitaire.html", category: "Page", keywords: "sanitaire plomberie raccords robinetterie adoucisseurs desco waterfront novellini" },
  { title: "Isolation", url: "isolation.html", category: "Page", keywords: "isolation laine verre laine roche laine bois chanvre xps pur pir liege liège cellulose verre cellulaire vermiculite pan-terre" },
  { title: "Tapis de pierre", url: "tapis-de-pierre.html", category: "Page", keywords: "tapis de pierre résine resine pu vertical primaire granulats granulat" },

  { title: "Briques", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "brique briques vandersanden" },
  { title: "Blocs", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "bloc blocs béton beton" },
  { title: "Blocs cellulaires", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "blocs cellulaires ytong bloc cellulaire" },
  { title: "Blocs stepocs", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "stepocs bloc coffrant blocs coffrants" },
  { title: "Planchers", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "plancher planchers hourdis dalle" },
  { title: "Sables", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "sable sables" },
  { title: "Citernes eau de pluie", url: "gros-oeuvre.html", category: "Gros œuvre", keywords: "citerne citernes eau pluie récupération recuperation" },

  { title: "Velux", url: "toiture.html", category: "Toitures", keywords: "velux fenêtre fenetre toit" },
  { title: "EPDM", url: "toiture.html", category: "Toitures", keywords: "epdm membrane toiture plate étanchéité etancheite roofing" },
  { title: "Tôles", url: "toiture.html", category: "Toitures", keywords: "tôles toles bac acier couverture" },
  { title: "Zinc", url: "toiture.html", category: "Toitures", keywords: "zinc toiture" },
  { title: "Gouttières", url: "toiture.html", category: "Toitures", keywords: "gouttière gouttières gouttiere evacuation eau" },

  { title: "Graviers", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "gravier graviers" },
  { title: "Carrelages extérieurs", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "carrelage extérieur exterieur terrasse" },
  { title: "Couvres murs", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "couvre mur couvres murs" },
  { title: "Pavés en béton", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "pavés paves béton beton" },
  { title: "Bordures & filets d'eau", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "bordures filets d'eau filet eau" },
  { title: "Seuils en pierre bleue", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "seuil seuils pierre bleue" },
  { title: "Chalet", url: "amenagement-exterieur.html", category: "Aménagements", keywords: "chalet abri jardin" },

  { title: "Carrelages", url: "sols.html", category: "Sols", keywords: "carrelage carrelages" },

  { title: "Thys", url: "portes.html", category: "Portes", keywords: "thys portes" },
  { title: "Solid", url: "portes.html", category: "Portes", keywords: "solid portes" },
  { title: "Dor's", url: "portes.html", category: "Portes", keywords: "dors dor's portes" },

  { title: "Niko", url: "electricite.html", category: "Électricité", keywords: "niko prises interrupteurs" },
  { title: "Schneider", url: "electricite.html", category: "Électricité", keywords: "schneider electric" },
  { title: "Legrand", url: "electricite.html", category: "Électricité", keywords: "legrand" },
  { title: "ABB", url: "electricite.html", category: "Électricité", keywords: "abb" },
  { title: "Marlanvil", url: "electricite.html", category: "Électricité", keywords: "marlanvil" },
  { title: "TECO", url: "electricite.html", category: "Électricité", keywords: "teco" },

  { title: "Adoucisseurs", url: "sanitaire.html", category: "Sanitaire", keywords: "adoucisseurs adoucisseur eau" },
  { title: "Desco", url: "sanitaire.html", category: "Sanitaire", keywords: "desco sanitaire" },
  { title: "Thys Sanitaire", url: "sanitaire.html", category: "Sanitaire", keywords: "thys sanitaire salle de bain" },
  { title: "Waterfront", url: "sanitaire.html", category: "Sanitaire", keywords: "waterfront" },
  { title: "Novellini", url: "sanitaire.html", category: "Sanitaire", keywords: "novellini douche paroi" },

  { title: "Laine de verre", url: "isolation.html", category: "Isolation", keywords: "laine verre" },
  { title: "Laine de roche", url: "isolation.html", category: "Isolation", keywords: "laine roche" },
  { title: "Laine de bois", url: "isolation.html", category: "Isolation", keywords: "laine bois fibre bois" },
  { title: "Laine de chanvre", url: "isolation.html", category: "Isolation", keywords: "laine chanvre" },
  { title: "XPS", url: "isolation.html", category: "Isolation", keywords: "xps polystyrène extrudé polystyrene extrude" },
  { title: "PUR", url: "isolation.html", category: "Isolation", keywords: "pur polyuréthane polyurethane" },
  { title: "PIR", url: "isolation.html", category: "Isolation", keywords: "pir polyisocyanurate" },
  { title: "Mousse résolique", url: "isolation.html", category: "Isolation", keywords: "résolique resolique mousse" },
  { title: "Verre cellulaire", url: "isolation.html", category: "Isolation", keywords: "verre cellulaire" },
  { title: "Cellulose", url: "isolation.html", category: "Isolation", keywords: "cellulose ouate" },
  { title: "Liège", url: "isolation.html", category: "Isolation", keywords: "liège liege" },
  { title: "Vermiculite", url: "isolation.html", category: "Isolation", keywords: "vermiculite" },
  { title: "Pan-terre", url: "isolation.html", category: "Isolation", keywords: "pan terre pan-terre" },

  { title: "Primaire bi composants", url: "tapis-de-pierre.html", category: "Tapis de pierre", keywords: "primaire bi composants" },
  { title: "Resine PU", url: "tapis-de-pierre.html", category: "Tapis de pierre", keywords: "resine résine pu polyurethane polyuréthane" },
  { title: "Resine PU vertical", url: "tapis-de-pierre.html", category: "Tapis de pierre", keywords: "resine résine pu vertical" },

  { title: "Bois", url: "bois.html", category: "Page", keywords: "bois panneaux pates a bois pâtes à bois osb mdf multiplex agglomere aggloméré chevron latte sls poutrelle volige unalit sous-toiture multi-film" },

  { title: "Bois", url: "bois.html", category: "Bois", keywords: "bois panneaux" },
  { title: "Pâtes à bois", url: "bois.html", category: "Bois", keywords: "pates a bois pâtes à bois liberon toupret" },

  { title: "Aggloméré", url: "bois.html", category: "Bois", keywords: "agglomere aggloméré panneau bois" },
  { title: "Chevron", url: "bois.html", category: "Bois", keywords: "chevron bois charpente" },
  { title: "Latte", url: "bois.html", category: "Bois", keywords: "latte bois" },
  { title: "Multiplex", url: "bois.html", category: "Bois", keywords: "multiplex lauan panneau bois" },
  { title: "MDF", url: "bois.html", category: "Bois", keywords: "mdf panneau fibre bois" },
  { title: "Multi-film", url: "bois.html", category: "Bois", keywords: "multi film multi-film panneau bois" },
  { title: "Panneau de sous-toiture", url: "bois.html", category: "Bois", keywords: "sous toiture sous-toiture panneau toiture" },
  { title: "OSB 3", url: "bois.html", category: "Bois", keywords: "osb osb3 osb 3 panneau bois" },
  { title: "Poutrelle", url: "bois.html", category: "Bois", keywords: "poutrelle bois" },
  { title: "SLS", url: "bois.html", category: "Bois", keywords: "sls bois" },
  { title: "Unalit Blanc", url: "bois.html", category: "Bois", keywords: "unalit blanc panneau" },
  { title: "Volige", url: "bois.html", category: "Bois", keywords: "volige bois toiture" },

  { title: "Blanc", url: "bois.html", category: "Pâtes à bois", keywords: "blanc pate a bois pâte à bois liberon" },
  { title: "Chêne clair", url: "bois.html", category: "Pâtes à bois", keywords: "chene clair chêne clair pate a bois pâte à bois liberon" },
  { title: "Chêne moyen", url: "bois.html", category: "Pâtes à bois", keywords: "chene moyen chêne moyen pate a bois pâte à bois liberon" },
  { title: "Chêne foncé", url: "bois.html", category: "Pâtes à bois", keywords: "chene fonce chêne foncé pate a bois pâte à bois liberon" },
  { title: "Noyer", url: "bois.html", category: "Pâtes à bois", keywords: "noyer pate a bois pâte à bois liberon" },
  { title: "Naturel", url: "bois.html", category: "Pâtes à bois", keywords: "naturel pate a bois pâte à bois liberon" },

  { title: "Extrême Wood", url: "bois.html", category: "Pâtes à bois", keywords: "extreme wood extrême wood toupret bois" },
  { title: "Hard Wood", url: "bois.html", category: "Pâtes à bois", keywords: "hard wood toupret bois" },
  { title: "Repair Wood", url: "bois.html", category: "Pâtes à bois", keywords: "repair wood toupret bois reparation réparation" },
  { title: "Wood Finish", url: "bois.html", category: "Pâtes à bois", keywords: "wood finish toupret bois finition" },

  // PARQUETS
{ title: "Parquets vinyle", url: "parquets.html", category: "Parquets", keywords: "parquet vinyle pvc rigid floor" },
{ title: "Dalles vinyle", url: "parquets.html", category: "Parquets", keywords: "dalles vinyle pvc sol" },
{ title: "Parquets stratifié", url: "parquets.html", category: "Parquets", keywords: "parquet stratifié stratifie laminate" },

{ title: "Natural", url: "parquets.html", category: "Parquets vinyle", keywords: "natural rigid floor vinyle parquet" },
{ title: "OAK", url: "parquets.html", category: "Parquets vinyle", keywords: "oak rigid floor vinyle parquet chene chêne" },
{ title: "R078", url: "parquets.html", category: "Parquets vinyle", keywords: "rocko r078 vinyle parquet" },

{ title: "OAK Grand Brown", url: "parquets.html", category: "Parquets stratifié", keywords: "oak grand brown stratifié parquet chene brun" },
{ title: "OAK Grand Titanium", url: "parquets.html", category: "Parquets stratifié", keywords: "oak grand titanium stratifié parquet chene gris" },
{ title: "OAK Summer beige", url: "parquets.html", category: "Parquets stratifié", keywords: "oak summer beige stratifié parquet chene beige" },
{ title: "OAK Welsh", url: "parquets.html", category: "Parquets stratifié", keywords: "oak welsh stratifié parquet chene naturel" },

// PEINTURES
{ title: "Peintures", url: "peintures.html", category: "Page", keywords: "peinture peintures levis diessner sikkens v33 basin cecil motip hammerite protections bois spray nuancier" },

{ title: "Levis", url: "peintures.html", category: "Peintures", keywords: "levis ambiance laque mur easyclean expert facade ferro floor" },
{ title: "Diessner", url: "peintures.html", category: "Peintures", keywords: "diessner dry protection premium primaire ultramatt perfect fine" },
{ title: "Sikkens", url: "peintures.html", category: "Protections du bois", keywords: "sikkens filter 7 plus hsl plus novatech" },
{ title: "V33", url: "peintures.html", category: "Protections du bois", keywords: "v33 bois jardin huile cire parquet terrasse vernis vitrificateur" },
{ title: "Basin", url: "peintures.html", category: "Protections du bois", keywords: "basin aquadux cire siccatif huile parquet cleaner wash wax vitrificateur" },
{ title: "Cecil", url: "peintures.html", category: "Protections du bois", keywords: "cecil tx203 fongicide" },
{ title: "Motip Spray", url: "peintures.html", category: "Peintures", keywords: "motip spray carat chrome bronze zinc fluorescent radiateur acrylique primer plastique tableau aimant" },
{ title: "Hammerite", url: "peintures.html", category: "Peintures", keywords: "hammerite rouille metal métal primer radiateur chaleur structure ultima" },

{ title: "Ambiance laque satin", url: "peintures.html", category: "Levis", keywords: "ambiance laque satin levis" },
{ title: "Ambiance laque mat", url: "peintures.html", category: "Levis", keywords: "ambiance laque mat levis" },
{ title: "Ambiance mur extra mat", url: "peintures.html", category: "Levis", keywords: "ambiance mur extra mat levis" },
{ title: "Ambiance mur metallic", url: "peintures.html", category: "Levis", keywords: "ambiance mur metallic levis metallique métallique" },
{ title: "Ambiance mur satin", url: "peintures.html", category: "Levis", keywords: "ambiance mur satin levis" },
{ title: "Duo sat mix", url: "peintures.html", category: "Levis", keywords: "duo sat mix levis" },
{ title: "Easyclean cuisine/sdb mat", url: "peintures.html", category: "Levis", keywords: "easyclean cuisine sdb salle de bain mat levis" },
{ title: "Easyclean cuisine/sdb sat", url: "peintures.html", category: "Levis", keywords: "easyclean cuisine sdb salle de bain satin levis" },
{ title: "Easyclean satin", url: "peintures.html", category: "Levis", keywords: "easyclean satin levis" },
{ title: "Expert mur", url: "peintures.html", category: "Levis", keywords: "expert mur levis" },
{ title: "Façade (mix)", url: "peintures.html", category: "Levis", keywords: "facade façade mix levis exterieur extérieur" },
{ title: "Ferro décor", url: "peintures.html", category: "Levis", keywords: "ferro decor décor levis" },
{ title: "Laque high gloss", url: "peintures.html", category: "Levis", keywords: "laque high gloss brillant levis" },
{ title: "Laque exp satin", url: "peintures.html", category: "Levis", keywords: "laque exp satin levis" },
{ title: "Laque rapide extérieur", url: "peintures.html", category: "Levis", keywords: "laque rapide exterieur extérieur levis" },
{ title: "Laque rég satin", url: "peintures.html", category: "Levis", keywords: "laque reg rég satin levis" },
{ title: "Levis floor regul", url: "peintures.html", category: "Levis", keywords: "levis floor regul sol" },

{ title: "Dry protection", url: "peintures.html", category: "Diessner", keywords: "dry protection diessner" },
{ title: "Premium", url: "peintures.html", category: "Diessner", keywords: "premium diessner" },
{ title: "Primaire", url: "peintures.html", category: "Diessner", keywords: "primaire diessner" },
{ title: "Ultramatt", url: "peintures.html", category: "Diessner", keywords: "ultramatt diessner ultra mat" },
{ title: "Perfect fine", url: "peintures.html", category: "Diessner", keywords: "perfect fine diessner" },

{ title: "Filter 7 Plus", url: "peintures.html", category: "Sikkens", keywords: "filter 7 plus sikkens" },
{ title: "Filter 7", url: "peintures.html", category: "Sikkens", keywords: "filter 7 sikkens" },
{ title: "HSL Plus", url: "peintures.html", category: "Sikkens", keywords: "hsl plus sikkens" },
{ title: "Novatech", url: "peintures.html", category: "Sikkens", keywords: "novatech sikkens" },

{ title: "Bois de jardin", url: "peintures.html", category: "V33", keywords: "bois de jardin v33" },
{ title: "Huile cire escaliers", url: "peintures.html", category: "V33", keywords: "huile cire escaliers v33" },
{ title: "Huile cire parquet", url: "peintures.html", category: "V33", keywords: "huile cire parquet v33" },
{ title: "Huile plan de travail mat", url: "peintures.html", category: "V33", keywords: "huile plan de travail mat v33" },
{ title: "Huile terrasse", url: "peintures.html", category: "V33", keywords: "huile terrasse v33" },
{ title: "Primer bois", url: "peintures.html", category: "V33", keywords: "primer bois v33" },
{ title: "Protection", url: "peintures.html", category: "V33", keywords: "protection v33" },
{ title: "Sol extrême", url: "peintures.html", category: "V33", keywords: "sol extreme extrême v33" },
{ title: "Vernis meuble", url: "peintures.html", category: "V33", keywords: "vernis meuble v33" },
{ title: "Vernis yacht", url: "peintures.html", category: "V33", keywords: "vernis yacht v33" },
{ title: "Vitrificateur escaliers", url: "peintures.html", category: "V33", keywords: "vitrificateur escaliers v33" },
{ title: "Vitrificateur parquet", url: "peintures.html", category: "V33", keywords: "vitrificateur parquet v33" },

{ title: "Aquadux", url: "peintures.html", category: "Basin", keywords: "aquadux basin" },
{ title: "Cire siccatif", url: "peintures.html", category: "Basin", keywords: "cire siccatif basin" },
{ title: "Huile maintenance", url: "peintures.html", category: "Basin", keywords: "huile maintenance basin" },
{ title: "Huile parquet color", url: "peintures.html", category: "Basin", keywords: "huile parquet color basin" },
{ title: "Intensive cleaner", url: "peintures.html", category: "Basin", keywords: "intensive cleaner basin" },
{ title: "Nettoyant wash wax", url: "peintures.html", category: "Basin", keywords: "nettoyant wash wax basin" },
{ title: "No visible huile", url: "peintures.html", category: "Basin", keywords: "no visible huile basin" },
{ title: "Vitrificateur 2 composants acryl", url: "peintures.html", category: "Basin", keywords: "vitrificateur 2 composants acryl basin" },

{ title: "TX203 fongicide", url: "peintures.html", category: "Cecil", keywords: "tx203 fongicide cecil" },

{ title: "Carat Argent", url: "peintures.html", category: "Motip Spray", keywords: "carat argent motip" },
{ title: "Carat Chrome Argent", url: "peintures.html", category: "Motip Spray", keywords: "carat chrome argent motip" },
{ title: "Carat Chrome Cuivre", url: "peintures.html", category: "Motip Spray", keywords: "carat chrome cuivre motip" },
{ title: "Carat Chrome Or", url: "peintures.html", category: "Motip Spray", keywords: "carat chrome or motip gold" },
{ title: "Carat Color", url: "peintures.html", category: "Motip Spray", keywords: "carat color motip couleur" },
{ title: "Carat Effet Paillettes Or", url: "peintures.html", category: "Motip Spray", keywords: "carat effet paillettes or motip" },
{ title: "Carat Fixation", url: "peintures.html", category: "Motip Spray", keywords: "carat fixation motip" },
{ title: "Carat Colle", url: "peintures.html", category: "Motip Spray", keywords: "carat colle glue motip" },
{ title: "Carat Polystyrène", url: "peintures.html", category: "Motip Spray", keywords: "carat polystyrene polystyrène motip" },
{ title: "Carat Primer Blanc", url: "peintures.html", category: "Motip Spray", keywords: "carat primer blanc motip" },
{ title: "Carat Primer", url: "peintures.html", category: "Motip Spray", keywords: "carat primer motip" },
{ title: "Embout / Buse", url: "peintures.html", category: "Motip Spray", keywords: "embout buse motip" },
{ title: "Craft Spray", url: "peintures.html", category: "Motip Spray", keywords: "craft spray motip" },
{ title: "Effet Bronze Antique", url: "peintures.html", category: "Motip Spray", keywords: "effet bronze antique motip" },
{ title: "Effet Bronze Cuivre", url: "peintures.html", category: "Motip Spray", keywords: "effet bronze cuivre motip" },
{ title: "Effet Bronze Or", url: "peintures.html", category: "Motip Spray", keywords: "effet bronze or gold motip" },
{ title: "Effet Chrome", url: "peintures.html", category: "Motip Spray", keywords: "effet chrome motip" },
{ title: "Effet Chrome Cuivre", url: "peintures.html", category: "Motip Spray", keywords: "effet chrome cuivre motip" },
{ title: "Effet Chrome Or", url: "peintures.html", category: "Motip Spray", keywords: "effet chrome or gold motip" },
{ title: "Vernis Transparent", url: "peintures.html", category: "Motip Spray", keywords: "vernis transparent clear varnish motip" },
{ title: "Email Porcelaine", url: "peintures.html", category: "Motip Spray", keywords: "email porcelaine motip" },
{ title: "Fluorescent", url: "peintures.html", category: "Motip Spray", keywords: "fluorescent fluor motip" },
{ title: "Blanc Frigidaire", url: "peintures.html", category: "Motip Spray", keywords: "blanc frigidaire frigo motip" },
{ title: "Graffiti EX", url: "peintures.html", category: "Motip Spray", keywords: "graffiti ex motip" },
{ title: "Métallique", url: "peintures.html", category: "Motip Spray", keywords: "metallique métallique metallic motip" },
{ title: "Radiateur", url: "peintures.html", category: "Motip Spray", keywords: "radiateur motip" },
{ title: "Zinc", url: "peintures.html", category: "Motip Spray", keywords: "zinc motip" },
{ title: "Karat Effet Paillettes", url: "peintures.html", category: "Motip Spray", keywords: "karat effet paillettes motip" },
{ title: "Haute Température", url: "peintures.html", category: "Motip Spray", keywords: "haute temperature température ht motip" },
{ title: "Acrylique", url: "peintures.html", category: "Motip Spray", keywords: "acrylique spray acryl motip" },
{ title: "Profi Spray", url: "peintures.html", category: "Motip Spray", keywords: "profi spray motip" },
{ title: "Primer Plastique", url: "peintures.html", category: "Motip Spray", keywords: "primer plastique motip" },
{ title: "Tableau + Aimant", url: "peintures.html", category: "Motip Spray", keywords: "tableau aimant motip" },

{ title: "Spray 600°", url: "peintures.html", category: "Hammerite", keywords: "spray 600 hammerite haute chaleur" },
{ title: "Base", url: "peintures.html", category: "Hammerite", keywords: "base hammerite" },
{ title: "Color", url: "peintures.html", category: "Hammerite", keywords: "color hammerite" },
{ title: "Convertisseur de rouille", url: "peintures.html", category: "Hammerite", keywords: "convertisseur rouille hammerite" },
{ title: "Décap’rouille", url: "peintures.html", category: "Hammerite", keywords: "decap rouille décap rouille hammerite" },
{ title: "Dégraisse métal", url: "peintures.html", category: "Hammerite", keywords: "degraisse metal dégraisse métal hammerite" },
{ title: "Diluant / nettoyant pinceau", url: "peintures.html", category: "Hammerite", keywords: "diluant nettoyant pinceau hammerite" },
{ title: "Primer beige", url: "peintures.html", category: "Hammerite", keywords: "primer beige hammerite" },
{ title: "Primer non ferreux", url: "peintures.html", category: "Hammerite", keywords: "primer non ferreux hammerite" },
{ title: "Radiateur blanc", url: "peintures.html", category: "Hammerite", keywords: "radiateur blanc hammerite" },
{ title: "Résistante chaleur noir", url: "peintures.html", category: "Hammerite", keywords: "resistante chaleur noir résistante hammerite" },
{ title: "Structure", url: "peintures.html", category: "Hammerite", keywords: "structure hammerite" },
{ title: "Ultima", url: "peintures.html", category: "Hammerite", keywords: "ultima hammerite" },

// PLÂTRES & ENDUITS
{ title: "Plâtres & Enduits", url: "platres.html", category: "Page", keywords: "platres plâtres enduits plaques platre plâtre bandes joints poudres pates sprays accessoires visserie cornieres" },

{ title: "Plaques de plâtre", url: "platres.html", category: "Plâtres & Enduits", keywords: "plaques de platre plaques de plâtre gyproc gyplat hydro feu 4ak" },
{ title: "Bandes à joints", url: "platres.html", category: "Plâtres & Enduits", keywords: "bandes a joints bandes à joints fibatape hpx armee armée papier" },
{ title: "Poudres", url: "platres.html", category: "Plâtres & Enduits", keywords: "poudres wr unique x pro fix finish goldband mp 75 perlfix snelband snelgips fibarex humi block reboucheur toupret g" },
{ title: "Pâtes & sprays", url: "platres.html", category: "Plâtres & Enduits", keywords: "pates et sprays pâtes et sprays f2f filler pasta reno band airspray tx120 tx140 durcisseur fibacryl touprelex spray anti humidite" },
{ title: "Accessoires", url: "platres.html", category: "Plâtres & Enduits", keywords: "accessoires rouleau taloche palette platresse plâtresse" },
{ title: "Visserie", url: "platres.html", category: "Plâtres & Enduits", keywords: "visserie vis phosphatées autoforante bande pfs" },
{ title: "Cornières", url: "platres.html", category: "Plâtres & Enduits", keywords: "cornieres cornières galvanisee galvanisée fil trame trame" },

{ title: "Plaque plâtre", url: "platres.html", category: "Plaques de plâtre", keywords: "plaque platre plâtre gyproc" },
{ title: "Plaque de plâtre 4AK", url: "platres.html", category: "Plaques de plâtre", keywords: "plaque platre 4ak plâtre" },
{ title: "Plaque plâtre hydrofuge", url: "platres.html", category: "Plaques de plâtre", keywords: "plaque platre hydro hydrofuge plâtre" },
{ title: "Plaque plâtre résistante au feu", url: "platres.html", category: "Plaques de plâtre", keywords: "plaque platre resistante au feu rf plâtre" },
{ title: "Gyplat plâtre", url: "platres.html", category: "Plaques de plâtre", keywords: "gyplat platre plâtre" },

{ title: "Bande à joints fibre", url: "platres.html", category: "Bandes à joints", keywords: "bande a joints fibre fibatape" },
{ title: "Bande à joints HPX", url: "platres.html", category: "Bandes à joints", keywords: "bande a joints hpx" },
{ title: "Bande à joints armée", url: "platres.html", category: "Bandes à joints", keywords: "bande a joints armee armée" },
{ title: "Bande à joints papier 150 m", url: "platres.html", category: "Bandes à joints", keywords: "bande a joints papier 150m 150 m" },

{ title: "WR Unique", url: "platres.html", category: "Poudres", keywords: "wr unique gyproc" },
{ title: "X Pro", url: "platres.html", category: "Poudres", keywords: "x pro gyproc" },
{ title: "Fix & Finish", url: "platres.html", category: "Poudres", keywords: "fix and finish fix finish knauf" },
{ title: "Goldband", url: "platres.html", category: "Poudres", keywords: "goldband knauf" },
{ title: "MP 75", url: "platres.html", category: "Poudres", keywords: "mp75 mp 75 knauf" },
{ title: "Perlfix", url: "platres.html", category: "Poudres", keywords: "perlfix knauf" },
{ title: "Snelband", url: "platres.html", category: "Poudres", keywords: "snelband knauf" },
{ title: "Snelgips", url: "platres.html", category: "Poudres", keywords: "snelgips knauf" },
{ title: "Fill & Finish 60", url: "platres.html", category: "Poudres", keywords: "fill finish 60 toupret" },
{ title: "Fix Fill Joint 45", url: "platres.html", category: "Poudres", keywords: "fix fill joint 45 toupret" },
{ title: "Fibarex", url: "platres.html", category: "Poudres", keywords: "fibarex toupret" },
{ title: "Humi block", url: "platres.html", category: "Poudres", keywords: "humi block humiblock toupret humidite humidité" },
{ title: "Reboucheur", url: "platres.html", category: "Poudres", keywords: "reboucheur toupret" },
{ title: "Toupret G", url: "platres.html", category: "Poudres", keywords: "toupret g" },

{ title: "Joint & Finish", url: "platres.html", category: "Pâtes & sprays", keywords: "joint finish toupret" },
{ title: "F2F", url: "platres.html", category: "Pâtes & sprays", keywords: "f2f knauf" },
{ title: "Filler Pasta", url: "platres.html", category: "Pâtes & sprays", keywords: "filler pasta knauf" },
{ title: "Reno Band", url: "platres.html", category: "Pâtes & sprays", keywords: "reno band knauf" },
{ title: "Airspray G 25 kg", url: "platres.html", category: "Pâtes & sprays", keywords: "airspray g 25 kg toupret" },
{ title: "TX120 Sanéo", url: "platres.html", category: "Pâtes & sprays", keywords: "tx120 saneo sanéo toupret" },
{ title: "TX140", url: "platres.html", category: "Pâtes & sprays", keywords: "tx140 toupret" },
{ title: "Durcisseur 1 L", url: "platres.html", category: "Pâtes & sprays", keywords: "durcisseur 1l 1 l toupret" },
{ title: "Durcisseur aérosol", url: "platres.html", category: "Pâtes & sprays", keywords: "durcisseur aerosol aérosol toupret" },
{ title: "Fibacryl", url: "platres.html", category: "Pâtes & sprays", keywords: "fibacryl toupret" },
{ title: "Touprelex", url: "platres.html", category: "Pâtes & sprays", keywords: "touprelex toupret" },
{ title: "Spray anti humidité", url: "platres.html", category: "Pâtes & sprays", keywords: "spray anti humidite humidité toupret" },

{ title: "Rouleau à enduire 180 mm", url: "platres.html", category: "Accessoires", keywords: "rouleau a enduire 180 mm toupret" },
{ title: "Taloche polystyrène noire 27×18 cm", url: "platres.html", category: "Accessoires", keywords: "taloche polystyrene noire 27x18 27×18" },
{ title: "Taloche polystyrène 27×18 cm", url: "platres.html", category: "Accessoires", keywords: "taloche polystyrene 27x18 27×18" },
{ title: "Palette à joint droite", url: "platres.html", category: "Accessoires", keywords: "palette a joint droite" },
{ title: "Palette à joint inox 230 mm", url: "platres.html", category: "Accessoires", keywords: "palette a joint inox 230 mm" },
{ title: "Palette de plâtrier aluminium", url: "platres.html", category: "Accessoires", keywords: "palette de platrier plâtrier aluminium" },
{ title: "Taloche frottoir blanc 120×250 mm", url: "platres.html", category: "Accessoires", keywords: "taloche frottoir blanc 120x250 120×250" },
{ title: "Taloche gratton 14×24 cm", url: "platres.html", category: "Accessoires", keywords: "taloche gratton 14x24 14×24" },
{ title: "Taloche plastique 14×8 cm", url: "platres.html", category: "Accessoires", keywords: "taloche plastique 14x8 14×8" },
{ title: "Plâtresse coins arrondis 406×100 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse coins arrondis 406x100 406×100" },
{ title: "Plâtresse acier pointue 110×400 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse acier pointue 110x400 110×400" },
{ title: "Plâtresse inox dentée 12×12 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox dentee dentée 12x12 12×12" },
{ title: "Plâtresse acier 280 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse acier 280 mm" },
{ title: "Plâtresse inox dentée 10×10 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox dentee dentée 10x10 10×10" },
{ title: "Plâtresse inox dentée 8×8 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox dentee dentée 8x8 8×8" },
{ title: "Plâtresse inox dentée 6×6 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox dentee dentée 6x6 6×6" },
{ title: "Plâtresse inox 280×130 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox 280x130 280×130" },
{ title: "Plâtresse inox arrondie 120×305 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox arrondie 120x305 120×305" },
{ title: "Plâtresse inox 0,33 mm 350×110 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox 0,33 350x110 350×110" },
{ title: "Plâtresse inox 0,30 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox 0,30 mm" },
{ title: "Plâtresse inox 280 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox 280 mm" },
{ title: "Plâtresse inox 260 mm", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse inox 260 mm" },
{ title: "Plâtresse à chape", url: "platres.html", category: "Accessoires", keywords: "platresse plâtresse a chape à chape" },

{ title: "Vis phosphatées", url: "platres.html", category: "Visserie", keywords: "vis phosphatées platre plâtre" },
{ title: "Vis phosphatées autoforante", url: "platres.html", category: "Visserie", keywords: "vis phosphatées autoforante" },
{ title: "Vis phosphatées en bande", url: "platres.html", category: "Visserie", keywords: "vis phosphatées en bande" },
{ title: "Vis montage rapide PFS + S", url: "platres.html", category: "Visserie", keywords: "vis montage rapide pfs" },

{ title: "Cornière galvanisée", url: "platres.html", category: "Cornières", keywords: "corniere galvanisee galvanisée" },
{ title: "Cornière fil tramé", url: "platres.html", category: "Cornières", keywords: "corniere fil trame trame tramee tramé" },

// PRODUITS CIMENTAIRES
{ title: "Produits cimentaires", url: "produits-cimentaires.html", category: "Page", keywords: "produits cimentaires enduits cimentage betons bétons mortiers ciments chaux sols colles joints adjuvants primers reparations réparations" },

{ title: "Enduits de cimentage", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "enduits cimentage kam kam san map map e map l planiseal egaliss facade façade" },
{ title: "Bétons", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "betons bétons melange beton béton beton be fix béton" },
{ title: "Mortiers", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "mortiers mortier mortier prepare préparé mortier refractaire réfractaire mortier zm melange mortier" },
{ title: "Ciments", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "ciments ciment zc325 ciment blanc ciment scellement pr" },
{ title: "Chaux", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "chaux enci mc12.5 footcal supercalco" },
{ title: "Sols", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "sols chape stabilisé stabilise egaline" },
{ title: "Colles & joints", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "colles joints carrelages carrelage keraflex euroflex steinfuge ultracolor ultramastic joint pro" },
{ title: "Adjuvants", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "adjuvants soudalatex dry soudaplast mz weberad mid air superbond" },
{ title: "Primers", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "primers beton tack gips primer betokontakt stuc primer ecoprim grip plus primer g mapegum wps" },
{ title: "Réparations", url: "produits-cimentaires.html", category: "Produits cimentaires", keywords: "reparations réparations reno beton fibarex granirex touprelex" },

{ title: "Kam", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "kam sakret cimentage" },
{ title: "Kam San", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "kam san sakret cimentage" },
{ title: "Map", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "map sakret cimentage" },
{ title: "Map E", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "map e sakret cimentage" },
{ title: "Map L", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "map l sakret cimentage" },
{ title: "Planiseal 88", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "planiseal 88 mapei etancheite étanchéité" },
{ title: "Egaliss Facade", url: "produits-cimentaires.html", category: "Enduits de cimentage", keywords: "egaliss facade façade toupret" },

{ title: "Mélange béton", url: "produits-cimentaires.html", category: "Bétons", keywords: "melange beton mélange béton" },
{ title: "Beton BE", url: "produits-cimentaires.html", category: "Bétons", keywords: "beton be sakret" },
{ title: "Fix Béton", url: "produits-cimentaires.html", category: "Bétons", keywords: "fix beton fix béton sakret" },

{ title: "Mortier préparé", url: "produits-cimentaires.html", category: "Mortiers", keywords: "mortier prepare préparé knauf" },
{ title: "Mortier réfractaire", url: "produits-cimentaires.html", category: "Mortiers", keywords: "mortier refractaire réfractaire knauf" },
{ title: "Mortier ZM", url: "produits-cimentaires.html", category: "Mortiers", keywords: "mortier zm sakret" },
{ title: "Mélange mortier", url: "produits-cimentaires.html", category: "Mortiers", keywords: "melange mortier mélange mortier" },

{ title: "Ciment ZC325", url: "produits-cimentaires.html", category: "Ciments", keywords: "ciment zc325 diamur" },
{ title: "Ciment blanc", url: "produits-cimentaires.html", category: "Ciments", keywords: "ciment blanc knauf" },
{ title: "Ciment de scellement PR", url: "produits-cimentaires.html", category: "Ciments", keywords: "ciment scellement pr knauf" },

{ title: "Enci MC12.5", url: "produits-cimentaires.html", category: "Chaux", keywords: "enci mc12.5" },
{ title: "Footcal", url: "produits-cimentaires.html", category: "Chaux", keywords: "footcal" },
{ title: "Supercalco", url: "produits-cimentaires.html", category: "Chaux", keywords: "supercalco" },

{ title: "Chape", url: "produits-cimentaires.html", category: "Sols", keywords: "chape diamur" },
{ title: "Stabilisé", url: "produits-cimentaires.html", category: "Sols", keywords: "stabilise stabilisé diamur" },
{ title: "Egaline", url: "produits-cimentaires.html", category: "Sols", keywords: "egaline weberniv fiber" },

{ title: "Keraflex blanc", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "keraflex blanc mapei colle carrelage" },
{ title: "Keraflex gris", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "keraflex gris mapei colle carrelage" },
{ title: "Euroflex", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "euroflex sakret colle carrelage" },
{ title: "Steinfuge SF50", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "steinfuge sf50 joint" },
{ title: "Ultracolor plus 2kg", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "ultracolor plus 2kg mapei joint" },
{ title: "Ultracolor plus 5kg", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "ultracolor plus 5kg mapei joint" },
{ title: "Ultracolor plus 23kg", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "ultracolor plus 23kg mapei joint" },
{ title: "Ultramastic", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "ultramastic mapei" },
{ title: "Joint pro blanc", url: "produits-cimentaires.html", category: "Colles & joints", keywords: "joint pro blanc weber" },

{ title: "Soudalatex Dry", url: "produits-cimentaires.html", category: "Adjuvants", keywords: "soudalatex dry soudal" },
{ title: "Soudaplast-MZ", url: "produits-cimentaires.html", category: "Adjuvants", keywords: "soudaplast mz soudal" },
{ title: "Weberad Mid Air", url: "produits-cimentaires.html", category: "Adjuvants", keywords: "weberad mid air mics air" },
{ title: "Weberad superbond", url: "produits-cimentaires.html", category: "Adjuvants", keywords: "weberad superbond" },

{ title: "Beton tack", url: "produits-cimentaires.html", category: "Primers", keywords: "beton tack drago paint" },
{ title: "Gips primer", url: "produits-cimentaires.html", category: "Primers", keywords: "gips primer drago paint gyps primer" },
{ title: "Betokontakt", url: "produits-cimentaires.html", category: "Primers", keywords: "betokontakt knauf" },
{ title: "Stuc primer", url: "produits-cimentaires.html", category: "Primers", keywords: "stuc primer knauf" },
{ title: "Ecoprim grip plus", url: "produits-cimentaires.html", category: "Primers", keywords: "ecoprim grip plus mapei" },
{ title: "Primer g", url: "produits-cimentaires.html", category: "Primers", keywords: "primer g mapei" },
{ title: "Mapegum wps", url: "produits-cimentaires.html", category: "Primers", keywords: "mapegum wps mapei etancheite étanchéité" },

{ title: "Reno beton", url: "produits-cimentaires.html", category: "Réparations", keywords: "reno beton knauf" },
{ title: "Fibarex", url: "produits-cimentaires.html", category: "Réparations", keywords: "fibarex toupret" },
{ title: "Granirex", url: "produits-cimentaires.html", category: "Réparations", keywords: "granirex toupret" },
{ title: "Touprelex", url: "produits-cimentaires.html", category: "Réparations", keywords: "touprelex toupret" },

// RACCORDS PLOMBERIE
{ title: "Raccords plomberie", url: "raccords-plomberie.html", category: "Page", keywords: "raccord plomberie laiton bicone push pex alpex collecteur huot rexuo plasson geka tube alpex" },

{ title: "Laiton", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "laiton raccord filete fileté plomberie" },
{ title: "Bicône", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "bicone bicone raccord compression" },
{ title: "Push", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "push raccord rapide plomberie" },
{ title: "Collecteur", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "collecteur distribution eau chauffage" },
{ title: "Huot", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "huot raccord polyethylene pe" },
{ title: "Rexuo", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "rexuo raccord polyethylene pe" },
{ title: "Plasson", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "plasson raccord polyethylene pe" },
{ title: "Geka", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "geka raccord arrosage eau" },
{ title: "Alpex", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "pex alpex raccord multicouche" },
{ title: "Alpex à sertir", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "alpex sertir multicouche sertissage" },
{ title: "Tube Alpex", url: "raccords-plomberie.html", category: "Raccords plomberie", keywords: "tube alpex multicouche plomberie" },

// LAITON
{ title: "Allonge", url: "raccords-plomberie.html", category: "Laiton", keywords: "allonge laiton raccord" },
{ title: "Bouchon", url: "raccords-plomberie.html", category: "Laiton", keywords: "bouchon laiton raccord" },
{ title: "Coude femelle / femelle", url: "raccords-plomberie.html", category: "Laiton", keywords: "coude femelle femelle laiton" },
{ title: "Coude mâle / femelle", url: "raccords-plomberie.html", category: "Laiton", keywords: "coude male femelle laiton" },
{ title: "Coude union", url: "raccords-plomberie.html", category: "Laiton", keywords: "coude union laiton" },
{ title: "Bonnet", url: "raccords-plomberie.html", category: "Laiton", keywords: "bonnet laiton raccord" },
{ title: "Culasse", url: "raccords-plomberie.html", category: "Laiton", keywords: "culasse laiton raccord" },
{ title: "Manchon", url: "raccords-plomberie.html", category: "Laiton", keywords: "manchon laiton raccord" },
{ title: "Nipple", url: "raccords-plomberie.html", category: "Laiton", keywords: "nipple mamelon laiton raccord" },
{ title: "Nipple réduit", url: "raccords-plomberie.html", category: "Laiton", keywords: "nipple reduit mamelon laiton" },
{ title: "Raccord union", url: "raccords-plomberie.html", category: "Laiton", keywords: "raccord union laiton" },
{ title: "Réduction femelle / femelle", url: "raccords-plomberie.html", category: "Laiton", keywords: "reduction femelle femelle laiton" },
{ title: "Réduction femelle / mâle", url: "raccords-plomberie.html", category: "Laiton", keywords: "reduction femelle male laiton" },
{ title: "Réduction mâle / femelle", url: "raccords-plomberie.html", category: "Laiton", keywords: "reduction male femelle laiton" },
{ title: "Té égal", url: "raccords-plomberie.html", category: "Laiton", keywords: "te egal laiton" },
{ title: "Té écrou libre", url: "raccords-plomberie.html", category: "Laiton", keywords: "te ecrou libre laiton" },
{ title: "Té écrou libre 45°", url: "raccords-plomberie.html", category: "Laiton", keywords: "te ecrou libre 45 laiton" },
{ title: "Tétine femelle", url: "raccords-plomberie.html", category: "Laiton", keywords: "tetine femelle laiton" },
{ title: "Tétine mâle", url: "raccords-plomberie.html", category: "Laiton", keywords: "tetine male laiton" },

// BICONE
{ title: "Coude femelle", url: "raccords-plomberie.html", category: "Bicône", keywords: "coude femelle bicone" },
{ title: "Coude mâle", url: "raccords-plomberie.html", category: "Bicône", keywords: "coude male bicone" },
{ title: "Coude femelle / femelle", url: "raccords-plomberie.html", category: "Bicône", keywords: "coude ff bicone" },
{ title: "Manchon", url: "raccords-plomberie.html", category: "Bicône", keywords: "manchon bicone" },
{ title: "Manchon réduit", url: "raccords-plomberie.html", category: "Bicône", keywords: "manchon reduit bicone" },
{ title: "Raccord femelle", url: "raccords-plomberie.html", category: "Bicône", keywords: "raccord femelle bicone" },
{ title: "Raccord mâle", url: "raccords-plomberie.html", category: "Bicône", keywords: "raccord male bicone" },
{ title: "Té égal", url: "raccords-plomberie.html", category: "Bicône", keywords: "te egal bicone" },

// PUSH
{ title: "Bague de montage", url: "raccords-plomberie.html", category: "Push", keywords: "bague montage push" },
{ title: "Insert", url: "raccords-plomberie.html", category: "Push", keywords: "insert push" },
{ title: "Jonction réduite", url: "raccords-plomberie.html", category: "Push", keywords: "jonction reduite push" },
{ title: "Vanne écrou libre", url: "raccords-plomberie.html", category: "Push", keywords: "vanne ecrou libre push" },

// COLLECTEURS
{ title: "Collecteur 2 sorties", url: "raccords-plomberie.html", category: "Collecteur", keywords: "collecteur 2 sorties chauffage eau" },
{ title: "Collecteur 3 sorties", url: "raccords-plomberie.html", category: "Collecteur", keywords: "collecteur 3 sorties chauffage eau" },
{ title: "Collecteur 4 sorties", url: "raccords-plomberie.html", category: "Collecteur", keywords: "collecteur 4 sorties chauffage eau" },
{ title: "Collecteur 5 sorties", url: "raccords-plomberie.html", category: "Collecteur", keywords: "collecteur 5 sorties chauffage eau" },
{ title: "Collecteur 6 sorties", url: "raccords-plomberie.html", category: "Collecteur", keywords: "collecteur 6 sorties chauffage eau" },

// TUBE ALPEX
{ title: "Tube Alpex", url: "raccords-plomberie.html", category: "Tube Alpex", keywords: "tube alpex multicouche" },
{ title: "Tube Alpex isolé rouge", url: "raccords-plomberie.html", category: "Tube Alpex", keywords: "tube alpex isole rouge multicouche" },
{ title: "Tube Alpex isolé bleu", url: "raccords-plomberie.html", category: "Tube Alpex", keywords: "tube alpex isole bleu multicouche" },
{ title: "Tube Alpex gainé rouge", url: "raccords-plomberie.html", category: "Tube Alpex", keywords: "tube alpex gaine rouge multicouche" },
{ title: "Tube Alpex gainé bleu", url: "raccords-plomberie.html", category: "Tube Alpex", keywords: "tube alpex gaine bleu multicouche" },

// ROBINETTERIE
{ title: "Robinetterie", url: "robinetterie.html", category: "Page", keywords: "robinetterie schutte grohe paffoni mitigeur evier lavabo eau froide melangeur douche bain douchette flexible barre accessoire" },

{ title: "Schütte", url: "robinetterie.html", category: "Robinetterie", keywords: "schutte schütte" },
{ title: "Grohe", url: "robinetterie.html", category: "Robinetterie", keywords: "grohe" },
{ title: "Paffoni", url: "robinetterie.html", category: "Robinetterie", keywords: "paffoni" },

{ title: "Mitigeur évier", url: "robinetterie.html", category: "Robinetterie", keywords: "mitigeur evier cuisine" },
{ title: "Mitigeur lavabo", url: "robinetterie.html", category: "Robinetterie", keywords: "mitigeur lavabo" },
{ title: "Robinet eau froide", url: "robinetterie.html", category: "Robinetterie", keywords: "robinet eau froide lave mains" },
{ title: "Mélangeur", url: "robinetterie.html", category: "Robinetterie", keywords: "melangeur mélangeur mural" },
{ title: "Mitigeur douche", url: "robinetterie.html", category: "Robinetterie", keywords: "mitigeur douche thermo thermostatique" },
{ title: "Mitigeur bains douche", url: "robinetterie.html", category: "Robinetterie", keywords: "mitigeur bain douche baignoire" },
{ title: "Douchette & flexible", url: "robinetterie.html", category: "Robinetterie", keywords: "douchette flexible colonne douche tete de douche" },
{ title: "Set barre de douche", url: "robinetterie.html", category: "Robinetterie", keywords: "set barre de douche rampe colonne" },
{ title: "Accessoire", url: "robinetterie.html", category: "Robinetterie", keywords: "accessoire support curseur inverseur barre" },

// SCHÜTTE
{ title: "Mitigeur evier WINDOW noir", url: "robinetterie.html", category: "Schütte", keywords: "window noir mitigeur evier rabattable" },
{ title: "Mitigeur lavabo DERBY chromé", url: "robinetterie.html", category: "Schütte", keywords: "derby chrome chromé mitigeur lavabo" },

{ title: "Mitigeur lavabo LOS ANGELES chromé", url: "robinetterie.html", category: "Schütte", keywords: "los angeles chrome chromé mitigeur lavabo" },
{ title: "Mitigeur lavabo LOS ANGELES noir", url: "robinetterie.html", category: "Schütte", keywords: "los angeles noir mitigeur lavabo" },
{ title: "Mitigeur lavabo LOS ANGELES chromé haut", url: "robinetterie.html", category: "Schütte", keywords: "los angeles lavabo haut chromé" },
{ title: "Mitigeur lavabo LOS ANGELES noir haut", url: "robinetterie.html", category: "Schütte", keywords: "los angeles lavabo haut noir" },
{ title: "Mitigeur douche LOS ANGELES chromé", url: "robinetterie.html", category: "Schütte", keywords: "los angeles douche chromé thermostatique" },
{ title: "Mitigeur douche LOS ANGELES noir mat", url: "robinetterie.html", category: "Schütte", keywords: "los angeles douche noir mat thermostatique" },
{ title: "Mitigeur bain douche LOS ANGELES chromé", url: "robinetterie.html", category: "Schütte", keywords: "los angeles bain douche chromé" },
{ title: "Mitigeur bain douche LOS ANGELES noir", url: "robinetterie.html", category: "Schütte", keywords: "los angeles bain douche noir" },

{ title: "Robinet eau froide ARAGON chromé", url: "robinetterie.html", category: "Schütte", keywords: "aragon eau froide chromé" },
{ title: "Robinet eau froide ARAGON noir", url: "robinetterie.html", category: "Schütte", keywords: "aragon eau froide noir" },

{ title: "Mitigeur lavabo DENVER noir", url: "robinetterie.html", category: "Schütte", keywords: "denver lavabo noir" },
{ title: "Mitigeur bain douche DENVER noir", url: "robinetterie.html", category: "Schütte", keywords: "denver bain douche noir" },
{ title: "Mitigeur douche DENVER noir mat", url: "robinetterie.html", category: "Schütte", keywords: "denver douche noir mat" },

{ title: "Robinet eau froide LIMA chromé", url: "robinetterie.html", category: "Schütte", keywords: "lima eau froide chromé" },

{ title: "Mitigeur douche VICO chromé", url: "robinetterie.html", category: "Schütte", keywords: "vico douche chromé" },
{ title: "Mitigeur bain douche VICO chromé", url: "robinetterie.html", category: "Schütte", keywords: "vico bain douche chromé" },

{ title: "Set de douche MADURA FRESH chromé", url: "robinetterie.html", category: "Schütte", keywords: "madura fresh set douche chromé" },
{ title: "Set de douche TOKIO chromé", url: "robinetterie.html", category: "Schütte", keywords: "tokio set douche chromé" },
{ title: "Set de douche TOKIO noir mat", url: "robinetterie.html", category: "Schütte", keywords: "tokio set douche noir mat" },
{ title: "Set de douche TRENTO noir mat", url: "robinetterie.html", category: "Schütte", keywords: "trento set douche noir mat" },
{ title: "GRAN CANARIA set douche de pluie noir mat", url: "robinetterie.html", category: "Schütte", keywords: "gran canaria douche pluie noir mat mitigeur thermostatique" },
{ title: "Set de douche OCEAN chromé anthracite", url: "robinetterie.html", category: "Schütte", keywords: "ocean set douche chromé anthracite" },
{ title: "Set de douche MADEIRA chromé", url: "robinetterie.html", category: "Schütte", keywords: "madeira set douche chromé" },

{ title: "KARIBIK Douchette à main chromé/gris clair", url: "robinetterie.html", category: "Schütte", keywords: "karibik douchette main chromé gris" },
{ title: "KARIBIK Douchette à main graphite mat", url: "robinetterie.html", category: "Schütte", keywords: "karibik douchette graphite mat" },
{ title: "KARIBIK Douchette à main noir mat", url: "robinetterie.html", category: "Schütte", keywords: "karibik douchette noir mat" },
{ title: "HAWAII Douchette à main chromé/gris clair", url: "robinetterie.html", category: "Schütte", keywords: "hawaii douchette chromé gris carré" },
{ title: "HAWAII Douchette à main graphite mat", url: "robinetterie.html", category: "Schütte", keywords: "hawaii douchette graphite mat carré" },
{ title: "HAWAII Douchette à main noir mat", url: "robinetterie.html", category: "Schütte", keywords: "hawaii douchette noir mat carré" },
{ title: "SUMATRA douchette à main", url: "robinetterie.html", category: "Schütte", keywords: "sumatra douchette main chromé blanc" },

{ title: "BELLAQUA Douchette à main", url: "robinetterie.html", category: "Schütte", keywords: "bellaqua douchette" },
{ title: "NAPOLI Douchette à main", url: "robinetterie.html", category: "Schütte", keywords: "napoli douchette" },
{ title: "AQUA2SAVE Douchette à main", url: "robinetterie.html", category: "Schütte", keywords: "aqua2save douchette" },
{ title: "BARI Douchette à main", url: "robinetterie.html", category: "Schütte", keywords: "bari douchette" },
{ title: "MADURA Douche de tête", url: "robinetterie.html", category: "Schütte", keywords: "madura douche tete tête" },
{ title: "ADRIA Set de douchette", url: "robinetterie.html", category: "Schütte", keywords: "adria set douchette" },

{ title: "Flexible de douche 80 cm", url: "robinetterie.html", category: "Schütte", keywords: "flexible douche 80 cm" },
{ title: "Flexible de douche 125 cm", url: "robinetterie.html", category: "Schütte", keywords: "flexible douche 125 cm" },
{ title: "Flexible de douche 150 cm", url: "robinetterie.html", category: "Schütte", keywords: "flexible douche 150 cm" },
{ title: "Flexible de douche 175 cm", url: "robinetterie.html", category: "Schütte", keywords: "flexible douche 175 cm" },
{ title: "Flexible de douche 200 cm", url: "robinetterie.html", category: "Schütte", keywords: "flexible douche 200 cm" },

{ title: "FRESH Set barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "fresh set barre douche" },
{ title: "NAPOLI Set barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "napoli set barre douche" },
{ title: "ADRIA Set barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "adria set barre douche" },
{ title: "FLORENZ Set barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "florenz set barre douche" },
{ title: "RAVEN set barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "raven set barre douche noir mat" },

{ title: "Support de douchette", url: "robinetterie.html", category: "Schütte", keywords: "support douchette mural" },
{ title: "Curseur pour barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "curseur barre douche" },
{ title: "Pièce articulée", url: "robinetterie.html", category: "Schütte", keywords: "piece articulee articulée pivot" },
{ title: "STELLA Barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "stella barre douche" },
{ title: "SIGNO Barre de douche", url: "robinetterie.html", category: "Schütte", keywords: "signo barre douche reglable réglable" },
{ title: "AVIGNON inverseur 3 voies", url: "robinetterie.html", category: "Schütte", keywords: "avignon inverseur 3 voies" },

{ title: "Mitigeur evier GRANDE noir", url: "robinetterie.html", category: "Schütte", keywords: "grande evier noir" },
{ title: "Mitigeur evier DIZIANI noir", url: "robinetterie.html", category: "Schütte", keywords: "diziani evier noir" },

{ title: "Mitigeur lavabo PORTO chromé", url: "robinetterie.html", category: "Schütte", keywords: "porto lavabo chromé" },
{ title: "Mitigeur bain douche PORTO chromé", url: "robinetterie.html", category: "Schütte", keywords: "porto bain douche chromé" },
{ title: "Mitigeur douche PORTO chromé", url: "robinetterie.html", category: "Schütte", keywords: "porto douche chromé" },

{ title: "Set de douche pour lavabo", url: "robinetterie.html", category: "Schütte", keywords: "set douche lavabo chromé" },

{ title: "Mitigeur evier CORNWALL chromé", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier chromé" },
{ title: "Mitigeur evier CORNWALL inox", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier inox" },
{ title: "Mitigeur evier CORNWALL blanc", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier blanc" },
{ title: "Mitigeur evier CORNWALL graphite", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier graphite" },
{ title: "Mitigeur evier CORNWALL noir", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier noir" },
{ title: "CORNWALL Mitigeur évier or mat", url: "robinetterie.html", category: "Schütte", keywords: "cornwall evier or mat" },

{ title: "Mitigeur evier MIAMI graphite mat", url: "robinetterie.html", category: "Schütte", keywords: "miami evier graphite mat" },
{ title: "Mitigeur evier MIAMI noir", url: "robinetterie.html", category: "Schütte", keywords: "miami evier noir" },

{ title: "Mitigeur evier GLASGOW noir + douchette", url: "robinetterie.html", category: "Schütte", keywords: "glasgow evier noir douchette" },
{ title: "Mitigeur evier YORK chromé", url: "robinetterie.html", category: "Schütte", keywords: "york evier chromé" },

{ title: "LONDON Mitigeur évier chromé avec bec extractible", url: "robinetterie.html", category: "Schütte", keywords: "london evier chromé bec extractible" },
{ title: "LONDON Mitigeur évier inox avec bec extractible", url: "robinetterie.html", category: "Schütte", keywords: "london evier inox bec extractible" },
{ title: "Mitigeur evier LONDON noir + douchette", url: "robinetterie.html", category: "Schütte", keywords: "london evier noir douchette" },
{ title: "Mitigeur evier LONDON doré + douchette", url: "robinetterie.html", category: "Schütte", keywords: "london evier dore doré douchette" },

{ title: "Mitigeur evier CARDIFF noir", url: "robinetterie.html", category: "Schütte", keywords: "cardiff evier noir" },

// PAFFONI
{ title: "Paffoni Mitigeur évier Stick", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni stick evier" },
{ title: "Paffoni Mitigeur douche Stick", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni stick douche" },
{ title: "Paffoni Mitigeur evier Red + douchette", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni red evier douchette" },
{ title: "Candy mitigeur lavabo sans vidage chromé", url: "robinetterie.html", category: "Paffoni", keywords: "candy lavabo chromé" },
{ title: "Elle mitigeur lavabo avec vidage chromé", url: "robinetterie.html", category: "Paffoni", keywords: "elle lavabo chromé" },
{ title: "Light mitigeur lavabo col de cygne chromé", url: "robinetterie.html", category: "Paffoni", keywords: "light lavabo col de cygne chromé" },
{ title: "Paffoni robinet lave-mains", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni robinet lave mains eau froide" },
{ title: "Paffoni Mitigeur lavabo Stick", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni stick lavabo" },
{ title: "Paffoni Mitigeur douche Equo Star", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni equo star douche" },
{ title: "Paffoni Mitigeur bain douche Equo Star", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni equo star bain douche" },
{ title: "Paffoni Mitigeur bain douche Stick", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni stick bain douche" },
{ title: "Paffoni Mitigeur evier Nordica", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni nordica evier" },
{ title: "Paffoni Mitigeur evier bec haut", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni evier bec haut" },
{ title: "Paffoni Mitigeur bain douche thermos", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni thermos bain douche" },
{ title: "Paffoni Mitigeur bain douche thermos Equo Star", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni thermos equo star bain douche" },
{ title: "Paffoni Mitigeur evier Ringo", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni ringo evier" },
{ title: "Paffoni Mitigeur lavabo Light noir", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni light lavabo noir" },
{ title: "Paffoni Mitigeur lavabo Elle noir", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni elle lavabo noir" },
{ title: "Paffoni Mitigeur lavabo Red sans vidage noir", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni red lavabo noir" },
{ title: "Rampe de douche Paffoni Sofia 70 cm", url: "robinetterie.html", category: "Paffoni", keywords: "paffoni sofia rampe douche 70 cm" },
{ title: "Flexible douche 150 cm 1/2x1/2", url: "robinetterie.html", category: "Paffoni", keywords: "flexible douche 150 cm paffoni" },
{ title: "Flexible douche 200 cm 1/2x1/2", url: "robinetterie.html", category: "Paffoni", keywords: "flexible douche 200 cm paffoni" },

// GROHE
{ title: "Mitigeur évier Concetto mural", url: "robinetterie.html", category: "Grohe", keywords: "grohe concetto mural evier" },
{ title: "Mitigeur évier muralGrohe", url: "robinetterie.html", category: "Grohe", keywords: "grohe evier mural" },
{ title: "Robinet evier costa bec inf.", url: "robinetterie.html", category: "Grohe", keywords: "grohe costa evier bec inferieur" },
{ title: "Mélangeur mural bec sup. COSTA", url: "robinetterie.html", category: "Grohe", keywords: "grohe costa mélangeur mural bec superieur" },
{ title: "Robinet lavabo Bauloop Grohe", url: "robinetterie.html", category: "Grohe", keywords: "grohe bauloop lavabo" },
{ title: "Mitigeur lavabo+vid. eurosm.", url: "robinetterie.html", category: "Grohe", keywords: "grohe eurosmart lavabo vidage" },
{ title: "Robinet universel Grohe", url: "robinetterie.html", category: "Grohe", keywords: "grohe robinet universel" },
{ title: "Robinet lave-mains Bauloop", url: "robinetterie.html", category: "Grohe", keywords: "grohe bauloop lave mains" },
{ title: "Mitigeur de lavabo eurosmart", url: "robinetterie.html", category: "Grohe", keywords: "grohe eurosmart lavabo" },
{ title: "Mitigeur evier eurosmart", url: "robinetterie.html", category: "Grohe", keywords: "grohe eurosmart evier" },
{ title: "Mitigeur de cuisine loop", url: "robinetterie.html", category: "Grohe", keywords: "grohe loop cuisine" },
{ title: "Mitigeur evier K4", url: "robinetterie.html", category: "Grohe", keywords: "grohe k4 evier" },
{ title: "Mitigeur evier Eurosmart", url: "robinetterie.html", category: "Grohe", keywords: "grohe eurosmart evier cuisine" },
{ title: "Mitigeur de cuisine eurosmart douchette", url: "robinetterie.html", category: "Grohe", keywords: "grohe eurosmart cuisine douchette" },
{ title: "Mitigeur Douche 34827000 performance", url: "robinetterie.html", category: "Grohe", keywords: "grohe douche performance 34827000" },
{ title: "Flexible 175 1/2x1/2", url: "robinetterie.html", category: "Grohe", keywords: "grohe flexible 175" },
{ title: "Flexible 150 1/2x1/2", url: "robinetterie.html", category: "Grohe", keywords: "grohe flexible 150" },
{ title: "Flexible 125 1/2x1/2", url: "robinetterie.html", category: "Grohe", keywords: "grohe flexible 125" },
{ title: "Colonne de douche 26696000", url: "robinetterie.html", category: "Grohe", keywords: "grohe colonne douche 26696000" },
{ title: "Colonne de douche 26677000", url: "robinetterie.html", category: "Grohe", keywords: "grohe colonne douche 26677000" },

{ title: "Panneaux Rocko", url: "murs-interieurs.html", category: "Page", keywords: "rocko panneaux panneaux rocko catalogue rocko panneau mural revetement revêtement" },
{ title: "Panneau Rocko K190", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko k190 panneau rocko" },
{ title: "Panneau Rocko K365", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko k365 panneau rocko" },
{ title: "Panneau Rocko K551", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko k551 panneau rocko" },
{ title: "Panneau Rocko R109", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r109 panneau rocko" },
{ title: "Panneau Rocko R120", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r120 panneau rocko" },
{ title: "Panneau Rocko R130", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r130 panneau rocko" },
{ title: "Panneau Rocko R156", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r156 panneau rocko" },
{ title: "Panneau Rocko R157B", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r157b panneau rocko" },
{ title: "Panneau Rocko R160", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r160 panneau rocko" },
{ title: "Panneau Rocko R162B", url: "murs-interieurs.html", category: "Rocko", keywords: "rocko r162b panneau rocko" },
{ title: "Catalogue Rocko", url: "murs-interieurs.html", category: "Rocko", keywords: "catalogue rocko fiche rocko pdf rocko" },

// SEUILS
{ title: "Seuils", url: "seuils.html", category: "Page", keywords: "seuil seuils pierre seuil porte seuil beton seuil pierre bleue seuil fenetre" },

{ title: "Seuil 18 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 18 cm seuil pierre 18cm seuil beton 18cm" },
{ title: "Seuil 22 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 22 cm seuil pierre 22cm seuil beton 22cm" },
{ title: "Seuil 25 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 25 cm seuil pierre 25cm seuil beton 25cm" },
{ title: "Seuil 28 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 28 cm seuil pierre 28cm seuil beton 28cm" },

{ title: "Seuil 50 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 50 cm longueur seuil 50cm" },
{ title: "Seuil 60 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 60 cm longueur seuil 60cm" },
{ title: "Seuil 70 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 70 cm longueur seuil 70cm" },
{ title: "Seuil 80 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 80 cm longueur seuil 80cm" },
{ title: "Seuil 90 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 90 cm longueur seuil 90cm" },
{ title: "Seuil 100 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 100 cm longueur seuil 100cm" },
{ title: "Seuil 120 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 120 cm longueur seuil 120cm" },
{ title: "Seuil 150 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 150 cm longueur seuil 150cm" },
{ title: "Seuil 180 cm", url: "seuils.html", category: "Seuils", keywords: "seuil 180 cm longueur seuil 180cm" },

];